ARG VERSION=6

FROM centos:${VERSION}

RUN yum update -y && yum -y install \
    gdb \
    git \
    rpm-build \
    sudo \
    vim \
  && bash -c "$(curl -fsSL https://raw.githubusercontent.com/vesoft-inc/nebula/master/build_dep.sh)" \
  && yum clean all \
  && rm -rf /var/cache/yum

RUN mkdir -p /home/nebula

WORKDIR /home/nebula
