FROM rockylinux:9

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV LANG=en_US.utf8

RUN dnf install -y epel-release && \
    dnf config-manager --set-enabled crb && \
    dnf update -y && \
    dnf install -y \
    autoconf \
    curl-devel \
    expat-devel \
    gettext \
    glibc-devel \
    glibc-headers \
    gcc \
    gcc-c++ \
    # FIXME: Please remove following libev libraries after third party rebuilt.
    libev \
    libev-devel \
    m4 \
    make \
    ncurses-devel \
    openldap-devel \
    openssh-clients \
    openssl-devel \
    # for lcov
    perl-JSON \
    perl-PerlIO-gzip \
    perl-Digest-MD5 \
    python3-devel \
    python3-pip \
    readline-devel \
    rpm-build \
    sudo \
    unzip \
    vim \
    wget \
    xz \
    zlib-devel \
    # client
    libatomic \
    ninja-build \
    cmake \
    git \
    lsb-release \
    ccache \
    lcov \
   && dnf clean all && rm -rf /var/cache/dnf

WORKDIR /root

ENV CCACHE_CPP2=1

SHELL ["/bin/bash", "-c"]

# Install nebula third-party master
RUN git clone https://github.com/vesoft-inc/nebula-third-party.git \
  && cd nebula-third-party \
  && git checkout master \
  && ./install-third-party.sh \
  && cd .. && rm -rf nebula-third-party

# fastcov
RUN pip3 install --no-cache-dir fastcov

# Install ossutil
RUN curl https://gosspublic.alicdn.com/ossutil/install.sh | bash

#Install minio client
RUN if [ "$(uname -m)" = "x86_64" ]; then \
        curl -O https://dl.min.io/client/mc/release/linux-amd64/mc; \
    else \
        curl -O https://dl.min.io/client/mc/release/linux-arm64/mc; \
    fi \
    && chmod +x mc \
    && mv mc /usr/local/bin/
