#!/usr/bin/env bash

VER=7

if [ "$DOCKER_TAG" = "centos6" ]; then
  VER=6
elif [ "$DOCKER_TAG" = "centos7" ]; then
  VER=7
elif [ "$DOCKER_TAG" = "ubuntu1604" ]; then
  VER=xenial
elif [ "$DOCKER_TAG" = "ubuntu1804" ]; then
  VER=bionic
fi

docker build -t ${IMAGE_NAME} -f ${DOCKERFILE_PATH} --build-arg VERSION=${VER} .
