#!/usr/bin/env bash

VER=7

if [ "$DOCKER_TAG" = "centos6" ]; then
  VER=6
elif [ "$DOCKER_TAG" = "centos7" ]; then
  VER=7
elif [ "$DOCKER_TAG" = "ubuntu16" ]; then
  VER=16.04
elif [ "$DOCKER_TAG" = "ubuntu18" ]; then
  VER=18.04
fi

docker build -t ${IMAGE_NAME} -f ${DOCKERFILE_PATH} --build-arg VERSION=${VER} --build-arg AREA=U .